add basic UI
davidigbo/school-library pull request #4
Opened 2023-06-01 19:29 UTC by david30-maker

## In this pull request, I implemented the basic ui of the school library by following these steps"

- [ ] Your console app should behave in the same way as it is in the example.
- [ ] Create a app.rb file that will serve as your console app entry-point. It should have methods that do the following:
- [ ] List all books.
- [ ] List all people.
- [ ] Create a person (teacher or student, not a plain Person).
- [ ] Create a book.
- [ ] Create a rental.
- [ ] List all rentals for a given person id.
- [ ] In your main.rb define the entry point, this will be a method called main that is invoked at the end of your file. This method should do the following:
- [ ] Present the user with a list of options to perform.
- [ ] Lets users choose an option.
- [ ] If needed, ask for parameters for the option.
- [ ] Have a way to quit the app.

2023-06-01 19:47 UTC, addod19 requested changes
### Hi @david30-maker, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] PR looks great :fireworks: 


## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we fix our MIT license link, currently it is broken. Also let us kindly ensure the README file is professional by formatting the text nicely(Future features not properly formatted)
- [ ] It would be better if we fix the app, currently it is not working as expected
![Screenshot from 2023-06-01 19-41-30](https://github.com/david30-maker/school-library/assets/46388113/031aae16-635d-45b4-9eb7-ccc9d0def8d5)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing all commit messages :man_technologist: 
- Also, kindly delete all commented pieces of code, it makes the code base looks messy and difficult to understand

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 19:53 UTC, david30-maker commented
Thanks @addod19 for reviewing my project, I will implement all the required changes, but I want to understand this your  It would be better if we fix the app, currently it is not working as expected, please.

2023-06-01 20:25 UTC, addod19 commented
> Thanks @addod19 for reviewing my project, I will implement all the required changes, but I want to understand this your It would be better if we fix the app, currently it is not working as expected, please.

@david30-maker, as seen in the screenshot, we are supposed to get a working app, for example, when I run `ruby main.rb`, the app should list available options for a user to select, for example, to create a person, rental etc. Kindly check the project requirements for all the information

2023-06-01 21:18 UTC, david30-maker commented
Thanks @addod19

2023-06-01 23:08 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @david30-maker 🙋‍♂️

Good job so far!  I really appreciate the effort you put in!  **_However, there are few things that still need to be fixed. But you are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Correct Gitflow
- ✅ Descriptive PR and README file
- ✅ Correct Linters


## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 23:08 UTC, KanzaTahreem commented on README.Md
> -**[Add_association_setup]**
- [ ] Please note that the previous reviewer didn't suggest to remove the **_Future Features_** section. Please revert this change and format it to make your README more professional as suggested 🤓⛏
- [ ] Also, please note that the license link is still not working ⚠. It is redirecting to a **_File not found_** page. Please make sure to fix the link as well. 

  
  ![image](https://github.com/david30-maker/school-library/assets/106119105/55ef2d02-8e32-4615-992d-f96a1dd05638)

2023-06-01 23:08 UTC, KanzaTahreem commented on main.rb
- [ ] The app is not working as expected (as shown in the [video](https://www.youtube.com/watch?v=vkkgrhD6aXQ)). This is because you are not calling the `main` method to start the app ✨ This can be fixed by following code snippet 👇

![image](https://github.com/david30-maker/school-library/assets/106119105/4777909c-0c40-49a7-8b61-c18c60cff083)

- Even after starting the app, the following error is occurring 👇 This can be fixed by using `user_option` instead of `get_user_option` on line 17. However, even after that, the app is not working 😥

![image](https://github.com/david30-maker/school-library/assets/106119105/e4020b00-3c05-4751-8c41-f057dc93de76)

```
require_relative 'app'

def main
  app = App.new

  loop do
    # ... Rest of your code ...
  end
end

main  # Call the main method to start the app
```

2023-06-01 23:41 UTC, david30-maker commented
Thanks @KanzaTahreem for reviewing, I will implement the required changes

2023-06-02 23:07 UTC, addod19 requested changes
### Hi @david30-maker, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Awesome job so far addressing the comments from the previous review and making the app runs successfully :rocket: 

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we create a License.md file, currently when we click on the License link it takes us to a `404` page as seen below
![Screenshot from 2023-06-02 22-52-41](https://github.com/david30-maker/school-library/assets/46388113/786d7d05-0d0b-4e78-95a5-d4df2347bfb7)
- [ ] Also let us kindly try to implement the functionality seen in the [video](https://www.youtube.com/watch?v=vkkgrhD6aXQ). Here is how our app looks like
![Screenshot from 2023-06-02 22-57-18](https://github.com/david30-maker/school-library/assets/46388113/769a2335-1d8a-4c23-8b55-d64abc72c30e)

We are not suppose to ask a user for an ID. Please watch the video and make the app as seen in the video

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 02:12 UTC, david30-maker commented
Thanks @addod19 for reviewing my project, I will implement the required changes

2023-06-03 08:16 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @david30-maker 👋, 

Great job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 08:16 UTC, codepantha commented on app.rb
> +  end
- [ ] [OPTIONAL] Well done for removing the prompt for person ID as requested by the previous reviewer. However, your implementation of the process of creating a person is not completely in line with the video. Please consider following the specifications in the [video](https://www.youtube.com/watch?v=vkkgrhD6aXQ). Kindly note that this is only only optional because the previous reviewer missed it ❗ 
### Guideline
![image](https://github.com/david30-maker/school-library/assets/46839548/7e6b2f91-3f2d-4c2c-a1f0-3570548e34a2)
### Your Implementation
![image](https://github.com/david30-maker/school-library/assets/46839548/6d477670-053f-450b-a059-51252e187f1d)

2023-06-03 08:23 UTC, david30-maker commented
Thanks, @codepantha for approving my project, I implement the optional requirement

2023-06-03 08:23 UTC, merged

2023-06-03 10:16 UTC, addod19 commented on app.rb
> +  end
> * [ ]  [OPTIONAL] Well done for removing the prompt for person ID as requested by the previous reviewer. However, your implementation of the process of creating a person is not completely in line with the video. Please consider following the specifications in the [video](https://www.youtube.com/watch?v=vkkgrhD6aXQ). Kindly note that this is only only optional because the previous reviewer missed it exclamation
> 
> ### Guideline
> ![image](https://user-images.githubusercontent.com/46839548/243068976-7e6b2f91-3f2d-4c2c-a1f0-3570548e34a2.png)
> 
> ### Your Implementation
> ![image](https://user-images.githubusercontent.com/46839548/243069059-6d477670-053f-450b-a059-51252e187f1d.png)

@codepantha, how did i missed it when i showed the student a link to the video of the app, please kindly make sure you read the previous code reviewers comment before reviewing the student's project to avoid such things like this
![Screenshot from 2023-06-03 10-12-22](https://github.com/david30-maker/school-library/assets/46388113/827cf502-ceec-454a-9638-ca8d67d005f3)