Preserve data
davidigbo/school-library pull request #6
Opened 2023-06-07 09:16 UTC by TaiwoEnoch

## I @TaiwoEnoch and my partner @david30-maker create this PR to feature preserving data of the OOP school library following the below requirements ⬇️ 

- [ ] Check the documentation for Ruby's [JSON library](https://ruby-doc.org/stdlib-3.0.0/libdoc/json/rdoc/JSON.html).
- [ ] On exit from your app save all the data (books, people, and rentals) into JSON files. One per type of data you are storing and named accordingly (e.g. rentals.json)
- [ ] On startup of your app load all data from files. Remember to handle the case when one or more of the files are missing

.

2023-06-07 09:44 UTC, omarsalem7 requested changes
Hi @TaiwoEnoch, @david30-maker 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
<!---- There is no linter error present ✔️ -->
- The Pull Request has a proper title and description. ✔️
- Correct git-flow ✔️

## Required Changes ♻️

- [ ] Kindly consider calling the `main` method at the end of the main file, so the app can run properly

- [ ] _Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 09:44 UTC, omarsalem7 commented on app.rb
> +  preserve data
- [ ] Kindly make a comment for this text because it makes your app crash

2023-06-07 09:44 UTC, omarsalem7 commented on app.rb
> +  end
- [ ] Kindly consider the data to be saved in JSON files because when exiting the app is not saved and files for them not created also make sure to handle the case when one file or more is missing the app works properly

2023-06-07 09:57 UTC, david30-maker commented
Thanks, @omarsalem7 for reviewing our project, we will implement the required changes

2023-06-07 10:17 UTC, julie-ify requested changes
Hi @TaiwoEnoch and @david30-maker,

- Good code organization ✔️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 10:17 UTC, julie-ify commented on app.rb
> +
- [ ] Kindly remove commented code. It was not present during the previous review and it makes your code hard to read.

2023-06-07 10:17 UTC, julie-ify commented on app.rb
> +
- [ ] You have not implemented the change requested by the previous reviewer. When I run the app and create people, books, and rentals, and exit the app the data is not saved to any JSON files. But you are required to store the data in the JSON files.

- [ ] If the files do not exist, the app should create them automatically and save the data in them.

2023-06-07 21:19 UTC, davidigbo commented
Thank you, @julie-ify for reviewing our project, we will ensure all required changes are implemented

2023-06-07 21:38 UTC, Ismailco requested changes
### Hi @TaiwoEnoch, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

 ## Required Changes ♻️
- [ ] Good job on saving the data to a JSON file however when I remove the JSON files the app breaks, kindly make sure to fix this issue so the app creates new JSON files if no files exist

![Screenshot_20230607_223332](https://github.com/david30-maker/school-library/assets/25227022/2c0c67d6-d327-4493-a7a2-aceac48c10a4)
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 21:45 UTC, david30-maker commented
Thanks, @Ismailco for reviewing our project we will implement the change.

2023-06-08 08:08 UTC, BenMukebo approved these changes
### Hi @TaiwoEnoch, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- Great, Everyone has contributed code to the project. ✔️  
- On exit from the app check the data is being saved.  ✔️  
- On startup of the app load all data from files and handle the case when one or more of the files are missing :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 08:20 UTC, david30-maker commented
Thank you, @BenMukebo for approving our project.

2023-06-08 08:20 UTC, merged